Modify featurenets to be used with updatenets

diff --git a/.github/actions/create-featurenet/action.yml b/.github/actions/create-featurenet/action.yml
--- a/.github/actions/create-featurenet/action.yml
+++ b/.github/actions/create-featurenet/action.yml
@@ -39,10 +39,34 @@ inputs:
     description: "Set to 'true' to create a hook"
     required: false
     default: 'false'
+  featurenet-name:
+    description: 'Enter name instead of getting it from branch'
+    required: false
+    default: ''
 
 runs:
   using: "composite"
   steps:
+    - name: Validate inputs
+      shell: bash
+      runs: |
+        if [[ 
+          "${{ inputs.featurenet-name }}" != "" && \
+          ! "${{ inputs.featurenet-name }}" =~ ^[a-z0-9]{5,30}$
+        ]]
+        then
+          echo "!!! Invalid updatenet name"
+          exit 1
+        fi
+        if [[
+          "${{ inputs.aleph-node-image }}" != "testnet" && \
+          "${{ inputs.aleph-node-image }}" != "mainnet"
+        ]]
+        then
+          echo "!!! Invalid updatename node image tag"
+          exit 1
+        fi
+
     - name: Get branch name and commit SHA
       id: get-ref-properties
       uses: ./.github/actions/get-ref-properties
@@ -56,6 +80,7 @@ runs:
         aws-access-key-id: ${{ inputs.aws-access-key-id }}
         aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
         featurenet-keys-s3bucket-name: ${{ inputs.featurenet-keys-s3bucket-name }}
+        featurenet-name: ${{ inputs.featurenet-name }}
 
     - name: Build chainspec for Hotnet FE and send it to S3
       if: inputs.aleph-node-image == 'mainnet'
@@ -66,6 +91,7 @@ runs:
         aws-access-key-id: ${{ inputs.aws-access-key-id }}
         aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
         featurenet-keys-s3bucket-name: ${{ inputs.featurenet-keys-s3bucket-name }}
+        featurenet-name: ${{ inputs.featurenet-name }}
 
     - name: Checkout argocd apps repo
       uses: actions/checkout@v3
@@ -77,6 +103,9 @@ runs:
 
     - name: Start featurenet
       shell: bash
+      env:
+        # yamllint disable-line rule:line-length
+        APP_NAME: ${{ inputs.featurenet-name != '' && inputs.featurenet-name || format('{0}{1}, 'fe-', steps.get-ref-properties.outputs.branch-name-for-argo) }}
       run: |
         cd "${{ inputs.repo-apps-name }}"
         pr_image_tag="fe-${{ steps.get-ref-properties.outputs.branch-name-for-argo-with-sha }}"
@@ -86,13 +115,14 @@ runs:
           image_arg="${pr_image}"
         fi
         ./Ops.sh create-featurenet \
-          "fe-${{ steps.get-ref-properties.outputs.branch-name-for-argo }}" \
+          "${{ env.APP_NAME }}" \
           "${image_arg}"
 
     - name: Commit featurenet change
       uses: EndBug/add-and-commit@v9.1.1
       env:
-        APP_NAME: fe-${{ steps.get-ref-properties.outputs.branch-name-for-argo }}
+        # yamllint disable-line rule:line-length
+        APP_NAME: ${{ inputs.featurenet-name != '' && inputs.featurenet-name || format('{0}{1}, 'fe-', steps.get-ref-properties.outputs.branch-name-for-argo) }}
       with:
         author_name: AlephZero Automation
         author_email: alephzero@10clouds.com
@@ -101,12 +131,15 @@ runs:
         add: "*.yaml"
         cwd: "${{ inputs.repo-apps-name }}"
 
-    - name: Refresh Argo and wait for the deletion to be finished
+    - name: Refresh Argo and wait for the creation to be finished
       if: inputs.no-refresh != 'true'
+      env:
+        # yamllint disable-line rule:line-length
+        APP_NAME: ${{ inputs.featurenet-name != '' && inputs.featurenet-name || format('{0}{1}, 'fe-', steps.get-ref-properties.outputs.branch-name-for-argo) }}
       shell: bash
       run: |
         cd "${{ inputs.repo-apps-name }}"
         ./Ops.sh refresh-featurenets "${{ inputs.argo-host }}" \
           "${{ inputs.argo-sync-user-token }}" \
-          "fe-${{ steps.get-ref-properties.outputs.branch-name-for-argo }}" \
+          "${{ env.APP_NAME }}" \
           "${{ inputs.create-hook }}"
