A0-1816 Review

diff --git a/.github/actions/get-node-system-version/action.yml b/.github/actions/get-node-system-version/action.yml
--- a/.github/actions/get-node-system-version/action.yml
+++ b/.github/actions/get-node-system-version/action.yml
@@ -14,6 +14,14 @@ outputs:
 runs:
   using: composite
   steps:
+    - name: Validate action inputs
+      shell: bash
+      run: |
+        if [[ ${{ inputs.env }} != 'testnet' && ${{ inputs.env }} != 'mainnet' ]]; then
+          echo "Error: inputs.env should be either mainnet or testnet!"
+          exit 1
+        fi
+
     - name: Query RPC system.version
       id: rpc-system-version
       shell: bash
