Extract RUST_TOOLCHAIN_NIGHTLY var to a separate check

diff --git a/.github/workflows/_check-vars-and-secrets.yml b/.github/workflows/_check-vars-and-secrets.yml
--- a/.github/workflows/_check-vars-and-secrets.yml
+++ b/.github/workflows/_check-vars-and-secrets.yml
@@ -5,6 +5,11 @@ name: Check vars and secrets
 on:
   workflow_call:
     inputs:
+      check-dev-vars:
+        description: Should dev vars be checked
+        required: false
+        type: boolean
+        default: true
       check-vars:
         description: Should vars be checked
         required: false
@@ -24,6 +29,21 @@ jobs:
       - name: Debug input values
         run: |
           echo "${{ inputs.check-vars }} ${{ inputs.check-secrets }}"
+
+      - name: Check dev vars
+        run: |
+          if [[ "${{ inputs.check-dev-vars }}" != "true" ]]; then
+            echo "Skipping dev vars check"
+            exit 0
+          fi
+
+          if [[ \
+            -z "${{ vars.RUST_TOOLCHAIN_NIGHTLY }}" \
+          ]]; then
+            echo "!!! Some repository variables are either missing or empty."
+            echo "!!! Please check either repository or organization settings."
+            exit 1
+          fi
 
       - name: Check vars
         run: |
