Prepend 'fe-' prefix to all featurenets in its actions

diff --git a/.github/workflows/create-featurenet.yml b/.github/workflows/create-featurenet.yml
--- a/.github/workflows/create-featurenet.yml
+++ b/.github/workflows/create-featurenet.yml
@@ -32,8 +32,48 @@ on:
         required: true
 
 jobs:
+  validate-inputs:
+    name: Validate inputs
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Validate inputs
+        shell: bash
+        # yamllint disable rule:line-length
+        run: |
+          if [[
+          ! "${{ inputs.featurenet-name }}" =~ ^[a-z0-9][a-z0-9\-]{4,48}$
+          ]]
+          then
+            echo "!!! Invalid featurenet name"
+            exit 1
+          fi
+        # yamllint enable rule:line-length
+
+  get-final-names:
+    name: Get final names
+    runs-on: ubuntu-20.04
+    needs: [validate-inputs]
+    outputs:
+      final-featurenet-name: ${{ steps.get-final-names.outputs.final-featurenet-name }}
+      final-ws-hostname-name: ${{ steps.get-final-names.outputs.final-ws-hostname-name }}
+      final-deployment-name: ${{ steps.get-final-names.outputs.final-deployment-name }}
+    steps:
+      - name: Get final names
+        id: get-final-names
+        shell: bash
+        # yamllint disable rule:line-length
+        run: |
+          final_featurenet_name_local=${{ inputs.featurenet-name }}
+          final_ws_hostname=ws-${{ inputs.featurenet-name }}.dev.azero.dev
+          final_deployment_name=fe-${{ inputs.featurenet-name }}
+          echo "final-featurenet-name=$final_featurenet_name_local" >> $GITHUB_OUTPUT
+          echo "final-ws-hostname=$final_ws_hostname" >> $GITHUB_OUTPUT
+          echo "final-deployment-name=$final_deployment_name" >> $GITHUB_OUTPUT
+        # yamllint enable rule:line-length
+
   check-vars-and-secrets:
     name: Check vars and secrets
+    needs: [get-final-names]
     uses: ./.github/workflows/_check-vars-and-secrets.yml
     secrets: inherit
 
@@ -66,7 +106,7 @@ jobs:
     secrets: inherit
 
   create-featurenet:
-    needs: [push-featurnet-node-image-to-ecr]
+    needs: [push-featurnet-node-image-to-ecr, get-final-names]
     name: Create featurenet based on the PR
     runs-on: [self-hosted, Linux, X64, small]
     outputs:
@@ -87,7 +127,9 @@ jobs:
           repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
           argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
           featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
-          featurenet-name: ${{ inputs.featurenet-name }}
+          featurenet-name: ${{ needs.get-final-names.outputs.final-featurenet-name }}
+          git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
+          git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
 
       - name: Start featurenet Deployment
         uses: bobheadxi/deployments@v1.1.0
@@ -95,7 +137,7 @@ jobs:
         with:
           step: start
           token: ${{ secrets.CI_GH_TOKEN }}
-          env: ${{ inputs.featurenet-name }}
+          env: ${{ needs.get-final-names.outputs.final-deployment-name }}
           ref: ${{ github.head_ref }}
           override: true
 
@@ -109,8 +151,10 @@ jobs:
           ecr-public-registry: ${{ vars.ECR_PUBLIC_REGISTRY }}
           featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
           expiration: ${{ inputs.expiration == '' && '48h' || inputs.expiration }}
-          featurenet-name: ${{ inputs.featurenet-name }}
+          featurenet-name: ${{ needs.get-final-names.outputs.final-featurenet-name }}
           internal: "${{ inputs.internal }}"
+          git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
+          git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
 
       - name: Wait for the aleph-node binary to accept some blocks
         uses: ./.github/actions/wait-for-finalized-heads
@@ -118,7 +162,7 @@ jobs:
           gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
           repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
           # yamllint disable-line rule:line-length
-          json-rpc-endpoint: https://ws-${{ inputs.featurenet-name }}.dev.azero.dev
+          json-rpc-endpoint: https://${{ needs.get-final-names.outputs.final-ws-hostname }}
 
       - name: Remove deleted label if present
         uses: actions-ecosystem/action-remove-labels@v1.3.0
@@ -134,10 +178,10 @@ jobs:
           step: finish
           token: ${{ secrets.CI_GH_TOKEN }}
           status: ${{ job.status }}
-          env: ${{ inputs.featurenet-name }}
+          env: ${{ needs.get-final-names.outputs.final-deployment-name }}
           deployment_id: ${{ steps.deployment.outputs.deployment_id }}
           # yamllint disable-line rule:line-length
-          env_url: https://dev.azero.dev/?rpc=wss%3A%2F%2Fws-${{ inputs.featurenet-name }}.dev.azero.dev#/explorer
+          env_url: https://dev.azero.dev/?rpc=wss%3A%2F%2F${{ needs.get-final-names.outputs.final-ws-hostname }}#/explorer
           ref: ${{ github.head_ref }}
 
       - name: Remove deployment request label if exists
diff --git a/.github/workflows/delete-featurenet.yml b/.github/workflows/delete-featurenet.yml
--- a/.github/workflows/delete-featurenet.yml
+++ b/.github/workflows/delete-featurenet.yml
@@ -16,13 +16,50 @@ on:
         required: true
 
 jobs:
+  validate-inputs:
+    name: Validate inputs
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Validate inputs
+        shell: bash
+        # yamllint disable rule:line-length
+        run: |
+          if [[
+          ! "${{ inputs.featurenet-name }}" =~ ^[a-z0-9][a-z0-9\-]{4,48}$
+          ]]
+          then
+            echo "!!! Invalid featurenet name"
+            exit 1
+          fi
+        # yamllint enable rule:line-length
+
+  get-final-names:
+    needs: [validate-inputs]
+    name: Get final names
+    runs-on: ubuntu-20.04
+    outputs:
+      final-featurenet-name: ${{ steps.get-final-names.outputs.final-featurenet-name }}
+      final-deployment-name: ${{ steps.get-final-names.outputs.final-deployment-name }}
+    steps:
+      - name: Get final names
+        id: get-final-names
+        shell: bash
+        # yamllint disable rule:line-length
+        run: |
+          final_featurenet_name_local=${{ inputs.featurenet-name }}
+          final_deployment_name=fe-${{ inputs.featurenet-name }}
+          echo "final-featurenet-name=$final_featurenet_name_local" >> $GITHUB_OUTPUT
+          echo "final-deployment-name=$final_deployment_name" >> $GITHUB_OUTPUT
+        # yamllint enable rule:line-length
+
   check-vars-and-secrets:
+    needs: [get-final-names]
     name: Check vars and secrets
     uses: ./.github/workflows/_check-vars-and-secrets.yml
     secrets: inherit
 
   delete-featurenet:
-    needs: [check-vars-and-secrets]
+    needs: [check-vars-and-secrets, get-final-names]
     name: Delete featurenet
     runs-on: [self-hosted, Linux, X64, small]
     steps:
@@ -40,7 +77,9 @@ jobs:
           repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
           argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
           featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
-          featurenet-name: ${{ inputs.featurenet-name }}
+          featurenet-name: ${{ needs.get-final-names.outputs.final-featurenet-name }}
+          git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
+          git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
 
       - name: Remove created label if present
         uses: actions-ecosystem/action-remove-labels@v1.3.0
@@ -54,7 +93,7 @@ jobs:
         with:
           step: deactivate-env
           token: ${{ secrets.CI_GH_TOKEN }}
-          env: ${{ inputs.featurenet-name }}
+          env: ${{ needs.get-final-names.outputs.final-deployment-name }}
           desc: Environment was deleted
           debug: true
 
@@ -62,7 +101,7 @@ jobs:
         uses: strumwolf/delete-deployment-environment@v2
         with:
           token: ${{ secrets.CI_GH_TOKEN }}
-          environment: ${{ inputs.featurenet-name }}
+          environment: ${{ needs.get-final-names.outputs.final-deployment-name }}
 
       - name: Remove delete deployment request label if exists
         if: contains(github.event.pull_request.labels.*.name, 'trigger:delete-featurenet')
diff --git a/.github/workflows/updatenet-update.yml b/.github/workflows/updatenet-update.yml
--- a/.github/workflows/updatenet-update.yml
+++ b/.github/workflows/updatenet-update.yml
@@ -59,6 +59,27 @@ jobs:
             exit 1
           fi
 
+      - name: Get updatenet name
+        id: get-updatenet-name
+        shell: bash
+        # yamllint disable rule:line-length
+        run: |
+          if [[
+            "${{ inputs.name }}" != "" && \
+            ! "${{ inputs.name }}" =~ ^[a-z0-9][a-z0-9\-]{4,30}$
+          ]]
+          then
+            echo "!!! Invalid name"
+            exit 1
+          fi
+          final_updatenet_name_local=updnet-${{ inputs.name }}
+          final_deployment_name_local=updatenet-${final_updatenet_name_local}
+          final_ws_hostname_local=ws-fe-updnet-${final_updatenet_name_local}.dev.azero.dev
+          echo "final-updatenet-name=$final_updatenet_name_local" >> $GITHUB_OUTPUT
+          echo "final-deployment-name=$final_deployment_name_local" >> $GITHUB_OUTPUT
+          echo "final-ws-hostname=$final_ws_hostname_local" >> $GITHUB_OUTPUT
+        # yamllint enable rule:line-length
+
       - name: Checkout repo
         uses: actions/checkout@v4
 
@@ -68,7 +89,7 @@ jobs:
         with:
           step: start
           token: ${{ secrets.CI_GH_TOKEN }}
-          env: updatenet-${{ inputs.name }}
+          env: ${{ steps.get-updatenet-name.outputs.final-deployment-name }}
           override: true
 
       - name: Update featurenet data, app and deploy it
@@ -80,7 +101,7 @@ jobs:
           argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
           ecr-public-registry: ${{ vars.ECR_PUBLIC_REGISTRY }}
           featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
-          featurenet-name: fe-updnet-${{ inputs.name }}
+          featurenet-name: ${{ steps.get-updatenet-name.outputs.final-updatenet-name }}
           featurenet-aleph-node-image: ${{ inputs.destination }}
           rolling-update-partition: ${{ inputs.rolling-update-partition }}
           replicas: ${{ inputs.replicas }}
@@ -90,7 +111,7 @@ jobs:
         with:
           gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
           repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
-          json-rpc-endpoint: https://ws-fe-updnet-${{ inputs.name }}.dev.azero.dev
+          json-rpc-endpoint: https://${{ steps.get-updatenet-name.outputs.final-ws-hostname }}
 
       - name: Finish featurenet Deployment
         uses: bobheadxi/deployments@v1
@@ -99,7 +120,7 @@ jobs:
           step: finish
           token: ${{ secrets.CI_GH_TOKEN }}
           status: ${{ job.status }}
-          env: updatenet-${{ inputs.name }}
+          env: ${{ steps.get-updatenet-name.outputs.final-deployment-name }}
           deployment_id: ${{ steps.deployment.outputs.deployment_id }}
           # yamllint disable-line rule:line-length
-          env_url: https://dev.azero.dev/?rpc=wss%3A%2F%2Fws-fe-updnet-${{ inputs.name }}.dev.azero.dev#/explorer
+          env_url: https://dev.azero.dev/?rpc=wss%3A%2F%2F${{ steps.get-updatenet-name.outputs.final-ws-hostname }}#/explorer
