test for c-c

diff --git a/.github/workflows/e2e-tests-contracts.yml b/.github/workflows/e2e-tests-contracts.yml
--- a/.github/workflows/e2e-tests-contracts.yml
+++ b/.github/workflows/e2e-tests-contracts.yml
@@ -46,9 +46,14 @@ jobs:
       - name: Install cargo-contract
         run: |
           sudo apt-get update && sudo apt-get install -y binaryen
-          cargo install cargo-dylint dylint-link
-          # revision merging Hans's PR changes [fix for node URL parsing ]
-          cargo install --git https://github.com/paritytech/cargo-contract.git --rev 5e6f941805e3d6032dbfa17771a887a362cb3460
+
+          if ! command -v cargo-contract --version &> /dev/null
+          then
+              echo "cargo-contracts executable could not be found. Installing"
+              cargo install cargo-dylint dylint-link
+              # revision merging Hans's PR changes [fix for node URL parsing ]
+              cargo install --git https://github.com/paritytech/cargo-contract.git --rev 5e6f941805e3d6032dbfa17771a887a362cb3460
+          fi
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
