force it

diff --git a/.github/workflows/e2e-tests-contracts.yml b/.github/workflows/e2e-tests-contracts.yml
--- a/.github/workflows/e2e-tests-contracts.yml
+++ b/.github/workflows/e2e-tests-contracts.yml
@@ -54,17 +54,20 @@ jobs:
           cargo-key: e2e-contracts
           cache-version: v1
           cargo-targets: e2e-tests-contracts/target/
-        
+
       - name: Install cargo-contract
         run: |
-          if ! command -v cargo-contract --version &> /dev/null
-          then
-              echo "cargo-contracts executable could not be found. Installing"
-              cd contracts/
               cargo install cargo-dylint dylint-link --force
               # revision merging Hans's PR changes [fix for node URL parsing ]
-              cargo install --git https://github.com/paritytech/cargo-contract.git --rev 5e6f941805e3d6032dbfa17771a887a362cb3460
-          fi
+              cargo install --git https://github.com/paritytech/cargo-contract.git --rev 5e6f941805e3d6032dbfa17771a887a362cb3460 --force
+          # if ! command -v cargo-contract --version &> /dev/null
+          # then
+          #     echo "cargo-contracts executable could not be found. Installing"
+          #     cd contracts/
+          #     cargo install cargo-dylint dylint-link --force
+          #     # revision merging Hans's PR changes [fix for node URL parsing ]
+          #     cargo install --git https://github.com/paritytech/cargo-contract.git --rev 5e6f941805e3d6032dbfa17771a887a362cb3460
+          # fi
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
