change intergration test to a bootnode setup
check finalization

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -125,16 +125,44 @@ jobs:
       - name: Verify nodes respond
         run: |
           validators=( damian tomasz zbyszko hansu )
+          rpc_port=9933
 
           for validator in "${validators[@]}"; do
             docker run --network container:$validator appropriate/curl:latest \
                        --retry 3 \
                        --retry-delay 10 \
                        -H "Content-Type: application/json" \
-                       -d '{"id":1, "jsonrpc":"2.0", "method": "rpc_methods"}' http://127.0.0.1:9933
+                       -d '{"id":1, "jsonrpc":"2.0", "method": "rpc_methods"}' http://127.0.0.1:$rpc_port
+            let rpc_port=$rpc_port+1
           done
 
+      # NOTE waits for the chain to make some progress
+      - name: Wait for approximately 2 sessions
+        run: sleep 7s
+        shell: bash
+
       # NOTE: more complex test scenarios can be run from here on out
+
+      # NOTE : makes RPC calls to the bootnode to obtain a last finalized block
+      # which by now should be non-zero if blocks are getting finalized
+      - name: Verify consensus is running
+        run: |
+         rpc_port=9933
+         zero="0x0"
+
+         BLOCK_HASH=$(docker run --network container:damian appropriate/curl:latest \
+                                 -H "Content-Type: application/json" \
+                                 -d '{"id":1, "jsonrpc":"2.0", "method": "chain_getFinalizedHead"}' http://127.0.0.1:$rpc_port | jq '.result')
+
+         LAST_FINALIZED=$(docker run --network container:damian appropriate/curl:latest \
+                                     -H "Content-Type: application/json"
+                                     -d '{"id":1, "jsonrpc":"2.0", "method": "chain_getBlock", "params": ['$BLOCK_HASH']}' http://127.0.0.1:$rpc_port | jq '.result.block.header.number')
+
+         echo "Last finalized block number: " $LAST_FINALIZED
+         if [[ $LAST_FINALIZED == $zero ]]; then
+          exit 1
+         fi
+         exit 0
 
       - name: Save docker image
         run: |
