Make yaml-validate workflow fail on errors

diff --git a/.github/workflows/yaml-validate.yml b/.github/workflows/yaml-validate.yml
--- a/.github/workflows/yaml-validate.yml
+++ b/.github/workflows/yaml-validate.yml
@@ -26,4 +26,19 @@ jobs:
           docker pull ${DOCKER_IMAGE}
           docker run --rm --name tmp-ghv -v $(pwd)/.github:/dot-github \
             ${DOCKER_IMAGE} \
-            validate -p /dot-github
+            validate -p /dot-github > validation_result
+          echo "------------------------------------------------"
+          cat validation_result
+          echo "------------------------------------------------"
+          cat validation_result | grep '^E' > validation_result_errors
+          if [[ $(cat validation_result_errors | wc -l) > 0 ]]; then
+            echo "!!!"
+            echo "!!! Errors have been found in GitHub YAML files!"
+            echo "!!!"
+            echo "------------------------------------------------"
+            cat validation_result_errors
+            echo "------------------------------------------------"
+            echo "!!! Please fix them!"
+            echo "!!!"
+            exit 1
+          fi
